apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: applications/app2/manifests
    repoURL: 'https://github.com/lallinger-arbeit/argocd-example.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
