apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: test
    server: 'https://kubernetes.default.svc'
  project: app1-part2-project
  source:
    path: differentPath
    repoURL: 'https://github.com/DifferentRepo.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
